import type { Config } from 'ziggy-js';

export interface AuthUser {
    id: number;
    ulid: string;
    name: string;
    email: string;
    email_verified_at?: string | null;
}

export interface Auth {
    user: AuthUser | null;
    roles: string[];
    permissions: string[];
    isSuperAdmin: boolean;
}

export interface Flash {
    success?: string;
    error?: string;
}

export interface PaginationLink {
    url: string | null;
    label: string;
    active: boolean;
}

export interface Paginated<T> {
    data: T[];
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
    links: PaginationLink[];
}

// Alias used by commerce/cms pages
export type PaginatedResponse<T> = Paginated<T>;

export interface Role {
    id: number;
    ulid: string;
    name: string;
    slug: string;
    description: string | null;
    level: number;
    is_system_role: boolean;
    is_custom_role: boolean;
    users_count?: number;
    permissions_count?: number;
    permissions?: Permission[];
}

export interface Permission {
    id: number;
    code: string;
    module: string;
    action: string;
    description: string | null;
}

export interface User {
    id: number;
    ulid: string;
    name: string;
    email: string;
    is_active: boolean;
    must_change_password: boolean;
    last_login_at: string | null;
    roles?: Role[];
    created_at: string;
}

/** Srcset map produced by ImageVariantService. Keys: 'original', 'webp', '320', '320_webp', etc. */
export type MediaSrcset = Record<string, string>;

export interface Media {
    id: number;
    ulid: string;
    disk: string;
    path: string;
    file_name: string;
    mime_type: string;
    extension: string;
    size: number;
    width: number | null;
    height: number | null;
    /** Responsive srcset variants generated by ImageVariantService. Null when not yet processed. */
    srcset: MediaSrcset | null;
    alt: string | null;
    title: string | null;
    collection: string | null;
    url?: string;
    created_at: string;
}

export interface Setting {
    id: number;
    group: string;
    key: string;
    value: unknown;
    type: string;
    is_public: boolean;
}

export interface ActivityLog {
    id: number;
    ulid: string;
    user_id: number | null;
    module: string;
    action: string;
    entity_type: string | null;
    entity_id: number | null;
    old_values: Record<string, unknown> | null;
    new_values: Record<string, unknown> | null;
    ip_address: string | null;
    created_at: string;
}

// ---------------------------------------------------------------------------
// Cart
// ---------------------------------------------------------------------------

export interface CartItemSummary {
    id: number;
    product_id: number;
    variation_id: number | null;
    name: string;
    sku: string | null;
    quantity: number;
    /** Integer minor units (cents/sen). */
    unit_price: number;
    /** Integer minor units (cents/sen). */
    line_total: number;
    image: string | null;
    url: string;
}

export interface CartTotals {
    /** Integer minor units. */
    subtotal: number;
    /** Integer minor units. */
    discount_total: number;
    /** Integer minor units. */
    shipping_total: number;
    /** Integer minor units. */
    tax_total: number;
    /** Integer minor units. */
    total: number;
}

export interface AppliedCoupon {
    code: string;
    valid: boolean;
    message: string | null;
    /** Discount amount in integer minor units. */
    discount: number;
}

export interface CartSummary {
    id: string | null;
    item_count: number;
    items: CartItemSummary[];
    /** ISO 4217 currency code, e.g. 'MYR'. */
    currency: string;
    totals: CartTotals;
    applied_coupon?: AppliedCoupon | null;
}

// ---------------------------------------------------------------------------
// Shipping & Checkout
// ---------------------------------------------------------------------------

export interface ShippingMethod {
    id: number;
    title: string;
    method_type: string;
    /** Cost in integer minor units. */
    cost: number;
    is_free: boolean;
}

export interface OrderConfirmationItem {
    name: string;
    sku: string;
    quantity: number;
    /** Integer minor units. */
    unit_price: number;
    /** Integer minor units. */
    total: number;
    meta: Record<string, string>;
}

export interface OrderConfirmationAddress {
    type: string;
    first_name: string;
    last_name: string;
    company: string | null;
    address_1: string;
    address_2: string | null;
    city: string;
    state: string | null;
    postcode: string | null;
    country: string;
    phone: string | null;
    email: string | null;
}

export interface OrderConfirmation {
    ulid: string;
    order_number: string;
    status: string;
    payment_status: string;
    payment_method: string;
    currency: string;
    /** Integer minor units. */
    subtotal: number;
    /** Integer minor units. */
    discount_total: number;
    /** Integer minor units. */
    shipping_total: number;
    /** Integer minor units. */
    tax_total: number;
    /** Integer minor units. */
    total: number;
    coupon_code: string | null;
    shipping_method: string | null;
    customer_note: string | null;
    created_at: string;
    items: OrderConfirmationItem[];
    addresses: OrderConfirmationAddress[];
}

// ---------------------------------------------------------------------------
// My Account
// ---------------------------------------------------------------------------

/** Curated order row passed to account order list / dashboard. */
export interface AccountOrderRow {
    ulid: string;
    order_number: string;
    status: string;
    payment_status: string;
    currency: string;
    /** Integer minor units. */
    total: number;
    item_count: number;
    created_at: string;
}

/** Detailed order item for OrderView page. */
export interface AccountOrderItem {
    name: string;
    sku: string | null;
    quantity: number;
    /** Integer minor units. */
    unit_price: number;
    /** Integer minor units. */
    subtotal: number;
    /** Integer minor units. */
    discount: number;
    /** Integer minor units. */
    tax: number;
    /** Integer minor units. */
    total: number;
    meta: Record<string, string>;
}

/** Address line within an order. Reuses OrderConfirmationAddress shape. */
export type AccountOrderAddress = OrderConfirmationAddress;

/** Status timeline entry — note included only for customer notes. */
export interface AccountStatusTimelineEntry {
    to_status: string;
    note: string | null;
    created_at: string;
}

/** Full order detail for OrderView page. */
export interface AccountOrderDetail {
    ulid: string;
    order_number: string;
    status: string;
    payment_status: string;
    payment_method: string;
    currency: string;
    /** Integer minor units. */
    subtotal: number;
    /** Integer minor units. */
    discount_total: number;
    /** Integer minor units. */
    shipping_total: number;
    /** Integer minor units. */
    tax_total: number;
    /** Integer minor units. */
    total: number;
    /** Integer minor units. */
    amount_refunded: number;
    coupon_code: string | null;
    shipping_method: string | null;
    customer_note: string | null;
    created_at: string;
    items: AccountOrderItem[];
    addresses: AccountOrderAddress[];
    timeline: AccountStatusTimelineEntry[];
}

/** Customer address record. */
export interface CustomerAddress {
    ulid: string;
    type: 'billing' | 'shipping';
    label: string | null;
    first_name: string;
    last_name: string;
    company: string | null;
    address_1: string;
    address_2: string | null;
    city: string;
    state: string | null;
    postcode: string | null;
    country: string;
    phone: string | null;
    is_default: boolean;
}

// ---------------------------------------------------------------------------
// Wishlist
// ---------------------------------------------------------------------------

/** Shared wishlist summary injected into all Inertia pages. */
export interface WishlistShared {
    /** Number of items in the user's wishlist (0 for guests). */
    count: number;
    /** Product IDs in the user's wishlist. Empty array for guests. */
    product_ids: number[];
}

/** One row in the My Account / Wishlist page. */
export interface WishlistItem {
    wishlist_id: number;
    product_id: number;
    variation_id: number | null;
    name: string;
    slug: string;
    /** Effective price in integer minor units (null for variable products). */
    price: number | null;
    regular_price: number;
    in_stock: boolean;
    image_url: string;
    image_alt: string;
}

// ---------------------------------------------------------------------------
// Compare
// ---------------------------------------------------------------------------

/** One product column in the Compare page. */
export interface CompareProduct {
    id: number;
    name: string;
    slug: string;
    price: number | null;
    regular_price: number;
    sale_price: number | null;
    in_stock: boolean;
    image_url: string;
    image_alt: string;
    brand: string | null;
    categories: string[];
    sku: string | null;
    type: string;
}

// ---------------------------------------------------------------------------
// A4: Design system tokens
// ---------------------------------------------------------------------------

export interface DesignSystemColor {
    key: string;
    name: string;
    value: string;
}

export interface DesignSystemTypographyPreset {
    key: string;
    label: string;
    fontFamily?: string;
    fontSize?: string;
    fontWeight?: string;
    lineHeight?: string;
}

export interface DesignSystemSpacingPreset {
    key: string;
    label: string;
    value: string;
}

export interface DesignSystemTokens {
    colors: DesignSystemColor[];
    typography: DesignSystemTypographyPreset[];
    spacing: DesignSystemSpacingPreset[];
}

// ---------------------------------------------------------------------------
// D8 — Open Graph / Twitter meta shared via Inertia props
// ---------------------------------------------------------------------------

/**
 * Page-level SEO / social-sharing metadata.
 *
 * Injected by each storefront controller into Inertia props under the key
 * `meta`. HandleInertiaRequests supplies site-level defaults; controllers
 * override with page-specific values.
 */
export interface StorefrontMeta {
    /** HTML <title> / og:title */
    title: string;
    /** meta description / og:description */
    description: string | null;
    /** Absolute URL for og:image */
    image: string | null;
    /** Canonical URL for the current page */
    canonical: string;
}

// ---------------------------------------------------------------------------
// Inertia page props
// ---------------------------------------------------------------------------

export type PageProps<T extends Record<string, unknown> = Record<string, unknown>> = T & {
    auth: Auth;
    flash: Flash;
    ziggy: Config & { location: string };
    /** Cart summary injected by HandleInertiaRequests on all storefront pages. */
    cart?: CartSummary;
    /** Wishlist summary injected by HandleInertiaRequests on all storefront pages. */
    wishlist?: WishlistShared;
    /** A4: Design system tokens — palette, typography presets, spacing presets. */
    designSystem?: DesignSystemTokens;
    /** D8: Open Graph / Twitter meta — populated by storefront controllers. */
    meta?: StorefrontMeta;
};
